### ISSUE TITLE
Error when run on x64 CPU

### ISSUE THREAD

**Issue by tgnreg** [Bassman2/MediaDevices#6] opened 2018-07-23 07:51 UTC
Hi, thank you for spend time to make this great project.
I got error about InteropServices.COMException when run on x64 CPU,
after call MediaDevice.Connect(), I cannot get info about SerialNumber, it throw exception.
Could you help me ?
Tks so much !

**Comment by Bassman2** [comment] 2018-07-27 21:22
Hi tgnreg, In principle MediaDevices runs on x64 CPUs. To help you I need more information about the used device and details about the exception. Please check if all calls to the MediaDevice Library are executed by the same thread. MediaDevice is not thread safe. Please check if the error also occurs with my test app. Regards Ralf

**Comment by Aldaviva** [comment] 2018-08-16 08:39
Hi Ralf,

I have run into the same error. When I run `MediaDeviceApp` without any changes, it works fine. When I switch the platform to x64, build, and run it again, `MediaDeviceApp` encounters this error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaDevices.MediaDriveInfo..ctor(MediaDevice device, String objectId) in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDevices\MediaDriveInfo.cs:line 23
   at MediaDevices.MediaDevice.<GetDrives>b__119_0(String o) in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDevices\MediaDevice.cs:line 1214
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MediaDevices.MediaDevice.GetDrives() in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDevices\MediaDevice.cs:line 1214
   at MediaDeviceApp.ViewModel.DriveViewModel.Update(MediaDevice device) in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDeviceApp\ViewModel\DriveViewModel.cs:line 28
   at MediaDeviceApp.ViewModel.MainViewModel.set_SelectedDevice(MediaDevice value) in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDeviceApp\ViewModel\MainViewModel.cs:line 150
   at MediaDeviceApp.ViewModel.MainViewModel.OnRefresh() in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDeviceApp\ViewModel\MainViewModel.cs:line 91
   at MediaDeviceApp.ViewModel.MainViewModel..ctor() in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDeviceApp\ViewModel\MainViewModel.cs:line 59
   at MediaDeviceApp.App.OnApplicationStartup(Object sender, StartupEventArgs e) in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDeviceApp\App.xaml.cs:line 23
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at MediaDeviceApp.App.Main()
```

I've been working with filesystem operations and it seems that when the platform is x64, all the `MediaDirectoryInfo` methods I have tried return `COMException` with the message `Element not found. (Exception from HRESULT: 0x80070490)`:

```cs
device.GetRootDirectory().EnumerateDirectories().ToList()
```
```
System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at PortableDeviceApiLib.IPortableDeviceValues.GetAt(UInt32 index, _tagpropertykey& pKey, tag_inner_PROPVARIANT& pValue)
   at MediaDevices.Internal.ComHelper.HasKeyValue(IPortableDeviceValues values, _tagpropertykey findKey)
   at MediaDevices.Internal.ComHelper.TryGetStringValue(IPortableDeviceValues values, _tagpropertykey key, String& value)
   at MediaDevices.MediaDevice.get_FriendlyName()
   at MediaDevices.MediaDevice.ToString()
```

I'm having trouble getting the debugger to give me anything more useful. Process Explorer tells me that the 64-bit version of `C:\Windows\System32\PortableDeviceTypes.dll` is loaded, but maybe there needs to be a 64-bit version of `Interop.PortableDeviceTypesLib.dll` (and `...ApiLib.dll`) as well? But I'm just guessing.

**Comment by Darkyenus** [comment] 2018-08-23 20:44
Hi, I am having the same problem. Unchecking "Prefer 32-bit" in Build settings causes the same exceptions as reported by Aldaviva. I am on Windows 7, 64-bit.

**Comment by Darkyenus** [comment] 2018-08-24 00:28
So I have been doing some investigating and I believe that these problems are caused by some strange memory corruption. I have tried to eliminate complexity around the crashing parts to better understand what is going on and then I encountered [something strange](https://github.com/Darkyenus/MediaDevices/commit/036a3c92f4838997bd41e0c82c4f8138e25ce93f#diff-e5d7e741eeabb6e870a02a2c217dfbbdR56).

The linked for loop kept getting into an endless loop, but only on debug. So I investigated with debugger, added some padding values and found that they indeed do get corrupted. (All of this happens when prefer 32 bit is turned off.) I am still not sure what exactly corrupts the memory and what to do with it (as a C# newbie), but it explains all of the strange crashes I have encountered.

@Bassman2, @Aldaviva, any ideas?

**Comment by Bassman2** [comment] 2018-09-03 13:41
Should be fixed with last update

**Closed by Bassman2** 2018-09-03 13:41 UTC

**Comment by Bassman2** [comment] 2018-10-10 15:05
Hello,

I have some speed optimizations built into MediaDevices available on Github.

You can tune it with Item.numObjectsToRequest.
This determines how much FileSystemEntries are requested at once.

Another idea is to use Stream.CopyTo with a larger bufferSize when copying files.

I would appreciate any feedback.

Regards
   Ralf


Von: Ben Hutchison <notifications@github.com>
Gesendet: Donnerstag, 16. August 2018 10:39
An: Bassman2/MediaDevices <MediaDevices@noreply.github.com>
Cc: Ralf Beckers <ralf.beckers@hotmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [Bassman2/MediaDevices] Error when run on x64 CPU (#6)


Hi Ralf,

I have run into the same error. When I run MediaDeviceApp without any changes, it works fine. When I switch the platform to x64, build, and run it again, MediaDeviceApp encounters this error:

System.NullReferenceException: Object reference not set to an instance of an object.

   at MediaDevices.MediaDriveInfo..ctor(MediaDevice device, String objectId) in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDevices\MediaDriveInfo.cs:line 23

   at MediaDevices.MediaDevice.<GetDrives>b__119_0(String o) in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDevices\MediaDevice.cs:line 1214

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)

   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

   at MediaDevices.MediaDevice.GetDrives() in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDevices\MediaDevice.cs:line 1214

   at MediaDeviceApp.ViewModel.DriveViewModel.Update(MediaDevice device) in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDeviceApp\ViewModel\DriveViewModel.cs:line 28

   at MediaDeviceApp.ViewModel.MainViewModel.set_SelectedDevice(MediaDevice value) in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDeviceApp\ViewModel\MainViewModel.cs:line 150

   at MediaDeviceApp.ViewModel.MainViewModel.OnRefresh() in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDeviceApp\ViewModel\MainViewModel.cs:line 91

   at MediaDeviceApp.ViewModel.MainViewModel..ctor() in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDeviceApp\ViewModel\MainViewModel.cs:line 59

   at MediaDeviceApp.App.OnApplicationStartup(Object sender, StartupEventArgs e) in C:\Users\Ben\Desktop\MediaDevices-b012c52a1a86516eda575039ff27d7adb94c818e\MediaDeviceApp\App.xaml.cs:line 23

   at System.Windows.Application.OnStartup(StartupEventArgs e)

   at System.Windows.Application.<.ctor>b__1_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at MediaDeviceApp.App.Main()

I've been working with filesystem operations and it seems that when the platform is x64, all the MediaDirectoryInfo methods I have tried return COMException with the message Element not found. (Exception from HRESULT: 0x80070490):

device.GetRootDirectory().EnumerateDirectories().ToList()

System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)

   at PortableDeviceApiLib.IPortableDeviceValues.GetAt(UInt32 index, _tagpropertykey& pKey, tag_inner_PROPVARIANT& pValue)

   at MediaDevices.Internal.ComHelper.HasKeyValue(IPortableDeviceValues values, _tagpropertykey findKey)

   at MediaDevices.Internal.ComHelper.TryGetStringValue(IPortableDeviceValues values, _tagpropertykey key, String& value)

   at MediaDevices.MediaDevice.get_FriendlyName()

   at MediaDevices.MediaDevice.ToString()

I'm having trouble getting the debugger to give me anything more useful. Process Explorer tells me that the 64-bit version of C:\Windows\System32\PortableDeviceTypes.dll is loaded, but maybe there needs to be a 64-bit version of Interop.PortableDeviceTypesLib.dll (and ...ApiLib.dll) as well? But I'm just guessing.
